---
- name: install | check archive stat
  stat:
    path: /tmp/{{ consul_template_archive_file }}
  register: consul_template_archive_stat


- name: install | download consul-template
  get_url:
    url: "{{ consul_template_download_url }}"
    dest: /tmp/{{ consul_template_archive_file }}
  when: not consul_template_archive_stat.stat.exists

- unarchive:
    src: "/tmp/{{ consul_template_archive_file }}"
    dest: "{{ consul_template_bin | dirname }}"
    copy: False
    creates: "{{ consul_template_bin }}"

- name: install | ensure bin permissions
  file:
    path: "{{ consul_template_bin }}"
    mode: 0770

- name: install | create consul-template directories
  file:
    path: '{{ item }}'
    mode: 775
    state: directory
  with_items:
    - "{{ consul_template_config_dir }}"
    - "{{ consul_template_templates_dir }}"

- name: install | render consul-template config
  template:
    src: consul-template.cfg
    dest: '{{ consul_template_config_file }}'
